matrix:
  include:
    - name: RxActions iOS
      xcode_scheme: RxActions iOS
      xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
      install: carthage bootstrap --platform iOS
      cache: ./Carthage
    - name: RxActions Mac
      xcode_scheme: RxActions Mac
      install: carthage bootstrap --platform Mac
      cache: ./Carthage
    - name: RxActions Swift Package Manager
      script: swift test
      cache: ./.build

osx_image: xcode10

language: swift
xcode_project: RxActions.xcodeproj
