matrix:
  include:
    - name: RxActions iOS
      xcode_scheme: RxActions iOS
      xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
    - name: RxActions Mac
      xcode_scheme: RxActions Mac

osx_image: xcode10

language: swift
install: carthage bootstrap
xcode_project: RxActions.xcodeproj
