matrix:
  include:
    - xcode_scheme: RxActions iOS
      xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
    - xcode_schem: RxActions Mac

osx_image: xcode9.4
language: swift
install: carthage bootstrap
xcode_project: RxActions.xcodeproj
