osx_image: xcode9.4
language: swift
install: carthage bootstrap
xcode_project: RxActions.xcodeproj
xcode_scheme:
  - 'RxActions iOS'
  - 'RxActions Mac'
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
